import 'package:hive/hive.dart';

part 'category.g.dart'; // This will be generated by Hive

@HiveType(typeId: 1) // Use a unique typeId (different from Expense)
class Category {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  Category({
    required this.id,
    required this.name,
  });
}
